@startuml
abstract Sensor {
    start()
    stop()
    isStarted()
    isStopped()
    {abstract} fetch()
    - {abstract} read()
}
class AnalogSensor {
    fetch()
    read()
}
AnalogSensor --|> Sensor
SensorsManager "1" --> "*" Sensor
@enduml