@startuml
actor Actor
Actor -> SensorsManager : stop()
activate SensorsManager
loop for each sensor in sensors
SensorsManager -> "sensor :: Sensor" : stop()
activate "sensor :: Sensor"
return
end
SensorsManager -> SensorsManager : stopped = true
return
@enduml